cartapp/urls.py
from django.urls import path
from .import views
app_name='cartapp'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/',views.full_remove,name='full_remove')

]

ecomproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cartapp.urls'))
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

search_app/urls.py
from django.urls import path
from .import views

app_name='search_app'

urlpatterns=[
    path('',views.search_result,name='search_result'),
]

shop/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from .import views
app_name='shop'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProductDetail,name='producatdetail'),


]

cartapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from shop.models import Products
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id
    
class CartItem(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='Cart_item'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name="Category"
        verbose_name_plural="Categories"
    
    def get_url(self):
        return reverse('shop:product_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Products(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(decimal_places=2, max_digits=10)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='products', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:producatdetail',args=[self.category.slug, self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    
    def __str__(self):
        return '{}'.format(self.name)

cartapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from shop.models import Products
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
    
def add_cart(request,product_id):
    product=Products.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity<cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()
    except:
        cart_item=CartItem.objects.create(product=product,cart=cart,quantity=1)
        cart_item.save()
    return redirect('cartapp:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart in cart_items:
            total+=(cart.product.price*cart.quantity)
            counter+=cart.quantity
    except ObjectDoesNotExist:
        pass
    context={'cart_items':cart_items,'total':total,'counter':counter}
    return render(request,"cart.html",context)

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Products,id=product_id)
    item=CartItem.objects.get(product=product,cart=cart)

    if item.quantity>1:
        item.quantity-=1
        item.save()
    else:
        item.delete()
    return redirect('cartapp:cart_detail')


def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Products,id=product_id)
    item=CartItem.objects.get(product=product,cart=cart)
    item.delete()
    return redirect('cartapp:cart_detail')

search_app/views.py
from django.shortcuts import render
from shop.models import Products
from django.db.models import Q
# Create your views here.

def search_result(request):
    products=None
    query=None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Products.objects.filter(Q(name__contains=query)|Q(description__contains=query))
        return render(request,"search.html",{'products':products,'query':query})

    

shop/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Products,Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list =Products.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Products.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page_num=int(request.GET.get('page','1'))
    except:
        page_num=1
    try:
        products=paginator.page(page_num)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    
    return render(request,'category.html',{'category':c_page,'products':products})

def ProductDetail(request,c_slug,product_slug):
    try:
        product=Products.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,"Product.html",{"products":product})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ad5414c00a.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{products.metadescription|truncatewords:155}}
{% endblock%}
{% block title %}
    {{products.name}}
{% endblock %}

{% block content%}
{% if not cart_items%}
    <div>
        <div class="text-centre">
            <h2 class="text-centre cart-title">Your Shopping Cart is Empty</h2>
            <p class="text-centre"><a href="{% url 'shop:allProdCat' %}">continue shopping</a></p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-centre"> 
            <br>
            <h1 class="text-centre">yOur cart</h1>
            <br>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <table class="table table-hover" id="cart-table">
                <thead class="cart-table-head">
                  <tr>
                    <th scope="col"></th>
                      <th scope="col">Product Name</th>
                  </tr>
                </thead>
                <tbody>
                   {% for item in cart_items %}
                       <tr>
                            <td>
                                <a href="{{item.product.get_absolute_url}}"><img src="{{item.product.image.url}}" alt="product image" class="float-left rounded" width="150px"></a>
                            </td>
                            <td class="text-left">
                                {{item.product.name}}
                                <br>
                                sku:{{item.product.id}}
                                <br>
                                price:{{item.product.price}}
                                <br>
                                quantity:{{item.quantity}}
                            </td>
                            <td>
                                {{item.sub_total}}
                            </td>
                            {% if item.quantity < item.product.stock %}
                            <td>
                                <a href="{% url 'cartapp:add_cart' item.product.id %}" class="custom-a"><i class="fa-solid fa-plus"></i></a>
                                <a href="{% url 'cartapp:cart_remove' item.product.id %}" class="custom-a"><i class="fa-solid fa-minus"></i></a>
                                <a href="{% url 'cartapp:full_remove' item.product.id %}" class="custom-icon"><i class="fa-solid fa-trash"></i></a>
                            </td>
                            {% else %}
                            <td>
                               
                                &nbsp;<a href="{% url 'cartapp:cart_remove' item.product.id %}" class="custom-a"><i class="fa-solid fa-minus"></i></a>
                                &nbsp;<a href="{% url 'cartapp:full_remove' item.product.id %}" class="custom-icon"><i class="fa-solid fa-trash"></i></a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-centre">
            <table class="table cart-table">
                <thead class="cart-table-head">
                    <tr>
                        <th>
                            checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Review your items before checkout
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            payable amount :<strong>{{total}}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block cart-button">continue shopping</a>

            </div>

        </div>

    </div>
    {% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}                            
    {%if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        E-store
    {% endif %}
{% endblock %}


{% block title %}
{% if category %}
    {{category.name}} E-store                          
{% else %}
    E-store
{% endif %}
{% endblock %}

{% block content%}
    {% if category%}
        <div>
            <div class="row row-class">
                <div class="mx-auto">
                    <p><a href="{% url 'shop:allProdCat' %}">our collections</a></p>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="container-fluid">
        {% if category %}
            <img class="my-image" src="{{category.image.url}}" width="100%" height="400px"  alt="{{category.name}}">
    </div>
    <div>
        <h2 class="text-center my-title">{{category.name}}</h2>
        <p class="text-justify">{{category.description}}</p>
    </div> 
    {% endif %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    {% for p in products.object_list %}
                    <div class="col-md-3">
                        <div class="card text-center" style="min-width: 18rem;" id="card">
                            <div class="card-body" id="items" >
                                <a href="{{p.get_url}}"><img class="card-img-top" src="{{p.image.url}} " height="200px" width="200px" alt="{{p.name}} "></a>
                                <h5 class="card-title">{{p.name}}</h5>
                                <h6>{{p.price}}</h6>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div>
                    {% if products.paginator.num_pages > 1 %}
                </div>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active{% endif %}">{{pg}}</a>
                
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <br>
        </div>
    </div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">&copy;All rights received</p>
</div>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{% static 'img/logo.jpg' %}" height="40px" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item" style="margin-left: 10px;">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item search-field">
                    <form class="form-inline my-2 my-lg-0" action="{%url 'search_app:search_result' %}" method="get">
                        {% csrf_token %}
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
                </li>
                <li class="nav-item search-button">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></i></button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:allProdCat' %}">All products</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Shop
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for l in links %}
                            <a class="dropdown-item" href="{{ l.get_url }}">{{ l.name }}</a>
                        {% endfor %}
                    </div>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fas fa-shopping-cart"></i>{{item_count}}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{products.metadescription|truncatewords:155}}
{% endblock%}
{% block title %}
    {{products.name}}
{% endblock %}

{% block content%}
    <div class="row product-row">
        <div class="mx-auto">
            <p><a href="{%url 'shop:allProdCat' %}">home</a>|<a href="{{products.category.get_url}}">{{products.category}}</a>|{{products.name}}</p>
        </div>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-centre">
                <div style="min-width: 18rem;">
                    <img style="margin-bottom: 10px;" src="{{products.image.url}}" width="300px" height="300px" alt="{{product.name}}">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                    <h2 class="text-justify product-title">{{products.name}}</h2>
                    <p class="text-justify product-description">{{products.description}}</p>
                    <p class="text-justify">{{products.price}}</p>
                    {% if products.stock <= 0 %}
                        <p class="text-justify">out of stock</p>
                    {% else %}
                        
                        <a style="margin-bottom: 10px;" class="btn btn-secondary" href="{% url 'cartapp:add_cart' products.id %}">add to cart</a> 
                    {% endif %} 
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
 

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{products.metadescription|truncatewords:155}}
{% endblock%}
{% block title %}
    {{productss.name}}
{% endblock %}

{% block content%}
<div class="text-center search-text">
    <p>searched for {{query}} </p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                {% for p in products%}
                <div class="col-md-3">
                    <div class="card text-center" style="min-width: 18rem;" id="card">
                        <div class="card-body" id="items" >
                            <a href="{{p.get_url}}"><img class="card-img-top" src="{{p.image.url}} " height="200px" width="200px" alt="{{p.name}} "></a>
                            <h5 class="card-title">{{p.name}}</h5>
                            <h6>{{p.price}}</h6>
                        </div>
                    </div>
                    {% empty %}
                    <div class="row mx-auto">
                        <p class="text-center search-text">no result</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
 
{% endblock %}